---
- name: Add key for ppa python repository
  apt_key: 
    keyserver: keyserver.ubuntu.com
    id: DB82666C
    state: present
  become: yes

- name: Add ppa python repository
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes
  become: yes

- name: Make sure required packages are present
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - python2.7
    - "apt-transport-https"

- name: Import the NodeSource GPG key into apt
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource deb repository
  become: yes
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
    state: present

- name: Add NodeSource deb-src repository
  become: yes
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
    state: present

- name: Make sure packages are present
  become: yes
  apt:
    name: nodejs
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages with NPM
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ nodejs.npm.packages }}"
